
#line 3 "lex.Int_yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define Int_yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define Int_yynoreturn __attribute__((__noreturn__))
#else
#define Int_yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (Int_yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((Int_yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE Int_yyrestart( Int_yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(Int_yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct Int_yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t Int_yy_size_t;
#endif

extern int Int_yyleng;

extern FILE *Int_yyin, *Int_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define Int_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up Int_yytext. */ \
        int Int_yyless_macro_arg = (n); \
        YY_LESS_LINENO(Int_yyless_macro_arg);\
		*Int_yy_cp = (Int_yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(Int_yy_c_buf_p) = Int_yy_cp = Int_yy_bp + Int_yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up Int_yytext again */ \
		} \
	while ( 0 )
#define unput(c) Int_yyunput( c, (Int_yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct Int_yy_buffer_state
	{
	FILE *Int_yy_input_file;

	char *Int_yy_ch_buf;		/* input buffer */
	char *Int_yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int Int_yy_buf_size;

	/* Number of characters read into Int_yy_ch_buf, not including EOB
	 * characters.
	 */
	int Int_yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int Int_yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int Int_yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int Int_yy_at_bol;

    int Int_yy_bs_lineno; /**< The line count. */
    int Int_yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int Int_yy_fill_buffer;

	int Int_yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via Int_yyrestart()), so that the user can continue scanning by
	 * just pointing Int_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t Int_yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t Int_yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * Int_yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (Int_yy_buffer_stack) \
                          ? (Int_yy_buffer_stack)[(Int_yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (Int_yy_buffer_stack)[(Int_yy_buffer_stack_top)]

/* Int_yy_hold_char holds the character lost when Int_yytext is formed. */
static char Int_yy_hold_char;
static int Int_yy_n_chars;		/* number of characters read into Int_yy_ch_buf */
int Int_yyleng;

/* Points to current character in buffer. */
static char *Int_yy_c_buf_p = NULL;
static int Int_yy_init = 0;		/* whether we need to initialize */
static int Int_yy_start = 0;	/* start state number */

/* Flag which is used to allow Int_yywrap()'s to do buffer switches
 * instead of setting up a fresh Int_yyin.  A bit of a hack ...
 */
static int Int_yy_did_buffer_switch_on_eof;

void Int_yyrestart ( FILE *input_file  );
void Int_yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE Int_yy_create_buffer ( FILE *file, int size  );
void Int_yy_delete_buffer ( YY_BUFFER_STATE b  );
void Int_yy_flush_buffer ( YY_BUFFER_STATE b  );
void Int_yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void Int_yypop_buffer_state ( void );

static void Int_yyensure_buffer_stack ( void );
static void Int_yy_load_buffer_state ( void );
static void Int_yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER Int_yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE Int_yy_scan_buffer ( char *base, Int_yy_size_t size  );
YY_BUFFER_STATE Int_yy_scan_string ( const char *Int_yy_str  );
YY_BUFFER_STATE Int_yy_scan_bytes ( const char *bytes, int len  );

void *Int_yyalloc ( Int_yy_size_t  );
void *Int_yyrealloc ( void *, Int_yy_size_t  );
void Int_yyfree ( void *  );

#define Int_yy_new_buffer Int_yy_create_buffer
#define Int_yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        Int_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Int_yy_create_buffer( Int_yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->Int_yy_is_interactive = is_interactive; \
	}
#define Int_yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        Int_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            Int_yy_create_buffer( Int_yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->Int_yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->Int_yy_at_bol)

/* Begin user sect3 */

#define Int_yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *Int_yyin = NULL, *Int_yyout = NULL;

typedef int Int_yy_state_type;

extern int Int_yylineno;
int Int_yylineno = 1;

extern char *Int_yytext;
#ifdef Int_yytext_ptr
#undef Int_yytext_ptr
#endif
#define Int_yytext_ptr Int_yytext

static Int_yy_state_type Int_yy_get_previous_state ( void );
static Int_yy_state_type Int_yy_try_NUL_trans ( Int_yy_state_type current_state  );
static int Int_yy_get_next_buffer ( void );
static void Int_yynoreturn Int_yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up Int_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(Int_yytext_ptr) = Int_yy_bp; \
	Int_yyleng = (int) (Int_yy_cp - Int_yy_bp); \
	(Int_yy_hold_char) = *Int_yy_cp; \
	*Int_yy_cp = '\0'; \
	(Int_yy_c_buf_p) = Int_yy_cp;
#define YY_NUM_RULES 32
#define YY_END_OF_BUFFER 33
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct Int_yy_trans_info
	{
	flex_int32_t Int_yy_verify;
	flex_int32_t Int_yy_nxt;
	};
static const flex_int16_t Int_yy_accept[147] =
    {   0,
        0,    0,   33,   31,   15,   14,   16,   31,   12,   13,
       10,   26,   31,   26,   11,   26,   26,   31,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   17,    0,   27,
       26,    0,   26,    0,   29,   28,   26,   26,   26,    0,
       26,    0,   26,   26,   26,   26,   26,   26,   26,   23,
       26,   26,   26,   26,   26,   17,   26,    0,   28,    0,
        0,   26,   26,    0,   25,    4,    0,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,    0,   29,    0,    0,   28,   30,   26,   26,   26,
       26,   26,   26,   26,   26,   26,    1,   26,   26,   26,

       26,    0,   28,   26,   26,   19,    2,   26,   26,   22,
       26,   26,   26,   26,   24,   26,    8,   26,    3,   26,
       26,    9,   26,   21,   26,   26,   18,   20,   26,   26,
       26,   26,   26,    5,   26,   26,   26,   26,   26,   26,
       26,    7,   26,   26,    6,    0
    } ;

static const YY_CHAR Int_yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    1,    7,
        8,    1,    9,   10,   11,   12,    1,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    1,    1,    1,
       14,    1,    1,    1,   15,   15,   15,   16,   17,   15,
       15,   15,   18,   15,   15,   15,   15,   15,   19,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       20,   21,   22,    1,   23,    1,   24,   25,   26,   27,

       28,   15,   29,   30,   31,   15,   15,   32,   15,   33,
       34,   35,   36,   37,   38,   39,   40,   15,   41,   42,
       15,   15,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR Int_yy_meta[43] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    1,    3,    3,    3,    3,    3,    4,
        3,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3
    } ;

static const flex_int16_t Int_yy_base[151] =
    {   0,
        0,  392,  377,  413,  413,  413,  413,  370,  413,  413,
      413,   31,  298,   42,  413,   36,   53,  223,   55,   57,
       47,   52,   49,   60,   68,   71,   72,    0,  221,  413,
       37,  203,  101,  188,   33,  102,  104,   11,  114,   77,
       94,  185,   67,   86,  102,   97,  107,  117,  112,  115,
      125,  132,  127,  129,  134,    0,  166,  171,  168,  177,
      181,  179,  149,  180,  413,  130,  163,  163,  165,  174,
      173,  185,  178,  189,  187,  197,  198,  188,  200,  209,
      229,  158,  132,  235,  127,  111,   83,  213,  217,  225,
      226,  222,  234,  229,  238,  233,  241,  248,  243,  250,

      246,   72,   59,  262,  253,  255,  257,  266,  264,  265,
      275,  273,  283,  280,  282,  284,  285,  292,  287,  300,
      297,  296,  310,  305,  307,  314,  309,  317,  318,  319,
      326,  328,  329,  330,  333,  340,  348,  349,  345,  352,
      347,  357,  359,  361,  362,  413,  402,   57,  404,  408
    } ;

static const flex_int16_t Int_yy_def[151] =
    {   0,
      146,    1,  146,  146,  146,  146,  146,  147,  146,  146,
      146,  148,  146,  149,  146,  149,  149,  146,  149,  149,
       20,   20,   20,   20,   20,   20,   20,  150,  147,  146,
      148,  146,  148,  146,  146,  146,   20,   20,   20,  146,
       20,  146,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,  150,  148,  146,  146,  146,
      146,  148,   20,  146,  146,   20,  146,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
      148,  146,  146,  146,  146,  146,  146,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,

       20,  146,  146,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,    0,  146,  146,  146,  146
    } ;

static const flex_int16_t Int_yy_nxt[456] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,    4,   11,
       12,   13,   14,   15,   16,   16,   16,   16,   17,    4,
       18,    4,   19,   16,   20,   21,   22,   16,   16,   16,
       23,   16,   16,   24,   16,   16,   16,   25,   16,   26,
       27,   16,   32,   33,   38,   35,   31,  146,  146,   58,
       38,   34,   31,   36,   37,   40,   34,   34,   39,   31,
       58,   40,   34,   31,  146,   31,  146,   31,  146,   39,
       41,  103,   40,   34,   40,   34,   40,   34,   46,   48,
       38,   49,   38,   47,  103,   38,   38,   43,   38,   64,
       44,   38,   50,   38,   51,   87,   45,   52,   65,   38,

       38,   38,   55,   53,   38,   38,   68,   38,   54,   66,
       38,   38,   36,   33,   59,   36,   37,   57,   60,   69,
       39,   34,   61,   86,   62,   38,   63,   38,   57,   60,
       71,   39,   70,   38,   72,   38,   38,   38,   74,   86,
       38,   38,   73,   38,   83,   38,   38,   38,   38,   75,
       38,   38,   76,   38,   38,   77,   38,   78,   38,   79,
       38,   63,   38,   38,   38,   38,   38,   38,   38,   38,
       83,   38,   80,   38,   61,   31,   62,  146,   81,   82,
       59,   82,   38,   83,   84,   85,   34,   85,   38,   86,
      146,   81,   64,   87,   88,   84,   38,   67,   38,   34,

       42,   65,   38,   89,   38,   90,   38,   38,   92,   93,
       91,   38,   38,   38,   96,   35,   94,   38,   38,   95,
       38,   38,   38,   99,   38,   30,   38,   38,   38,   97,
       38,   38,  100,   38,   98,   42,   38,   38,  101,   38,
      146,   81,   38,  102,  104,  102,   38,  103,   38,   34,
       38,  106,   38,  107,  105,   38,   38,  109,   38,   38,
      108,   38,   38,  111,   38,   38,   38,   38,   38,  112,
      110,   38,   38,   38,   38,  113,   38,   38,  115,  116,
       38,   38,  114,   38,  117,   38,   38,   38,   38,   38,
       38,  118,   38,  119,   38,   38,   38,   38,   38,   38,

      120,   38,  121,   38,   38,   38,   38,  124,   38,  123,
       35,  122,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,  125,   38,   38,   38,  127,  126,   38,
       38,   38,  129,   38,  128,   38,   38,  131,   38,   38,
       38,  133,   38,   38,   38,  130,   38,   38,   38,   38,
       38,   38,   38,   38,  132,  135,   38,   38,   38,   38,
      134,   38,  136,   38,  137,   38,   38,   38,   38,   38,
      138,  139,   38,   38,   30,  140,  146,  143,   38,   38,
       38,   38,   38,  141,   38,   38,   38,   38,   38,  142,
       38,   38,  144,  145,   38,   38,   38,   28,   38,  146,

       38,   38,   29,   29,   29,   29,   38,   38,   56,  146,
       56,   56,    3,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146
    } ;

static const flex_int16_t Int_yy_chk[456] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   12,   12,   38,   35,   16,   16,   31,   35,
       38,   12,   14,   14,   14,   16,   16,   31,   14,  148,
       35,   14,   14,   17,   17,   19,   19,   20,   20,   14,
       17,  103,   17,   17,   19,   19,   20,   20,   21,   22,
       21,   23,   23,   21,  102,   22,   21,   19,   23,   40,
       20,   22,   24,   24,   24,   87,   20,   25,   40,   24,

       43,   25,   27,   26,   26,   27,   43,   25,   26,   41,
       26,   27,   33,   33,   36,   37,   37,   33,   36,   44,
       37,   33,   39,   86,   39,   44,   39,   41,   33,   36,
       46,   37,   45,   41,   47,   45,   46,   37,   49,   85,
       47,   45,   48,   37,   83,   49,   47,   39,   50,   49,
       48,   49,   51,   39,   50,   52,   48,   53,   51,   54,
       53,   63,   54,   66,   51,   52,   53,   55,   54,   66,
       82,   52,   55,   55,   57,   67,   57,   57,   57,   58,
       59,   58,   63,   58,   59,   60,   57,   60,   63,   60,
       62,   62,   64,   61,   68,   59,   68,   42,   69,   62,

       34,   64,   68,   69,   69,   70,   71,   70,   72,   73,
       71,   73,   71,   70,   75,   32,   74,   73,   72,   74,
       75,   78,   74,   78,   72,   29,   75,   78,   74,   76,
       76,   77,   79,   79,   77,   18,   76,   77,   80,   79,
       81,   81,   80,   84,   88,   84,   88,   84,   80,   81,
       89,   90,   88,   91,   89,   92,   89,   93,   90,   91,
       92,   92,   94,   95,   90,   91,   96,   93,   94,   96,
       94,   95,   96,   93,   97,   98,   99,   95,  100,  101,
       97,   98,   99,  100,  104,  101,  105,   98,  106,  100,
      107,  105,  105,  108,  106,  104,  107,  109,  110,  108,

      109,  104,  111,  109,  110,  108,  112,  114,  111,  113,
       13,  112,  112,  114,  111,  115,  113,  116,  117,  114,
      119,  115,  113,  116,  117,  118,  119,  120,  118,  122,
      121,  118,  123,  120,  121,  122,  121,  126,  124,  120,
      125,  130,  127,  123,  124,  125,  125,  126,  127,  123,
      128,  129,  130,  126,  129,  132,  128,  129,  130,  131,
      131,  132,  133,  134,  135,  131,  135,  132,  133,  134,
      136,  137,  135,  136,    8,  138,    3,  141,  139,  136,
      141,  137,  138,  139,  139,  140,  141,  137,  138,  140,
      142,  140,  143,  144,  144,  145,  142,    2,  143,    0,

      144,  145,  147,  147,  147,  147,  149,  149,  150,    0,
      150,  150,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146
    } ;

static Int_yy_state_type Int_yy_last_accepting_state;
static char *Int_yy_last_accepting_cpos;

extern int Int_yy_flex_debug;
int Int_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define Int_yymore() Int_yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *Int_yytext;
#line 1 "bootscanner.l"
#line 2 "bootscanner.l"
/*-------------------------------------------------------------------------
 *
 * bootscanner.l
 *	  a lexical scanner for the bootstrap parser
 *
 * Portions Copyright (c) 1996-2005, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 *
 * IDENTIFICATION
 *	  $PostgreSQL: pgsql/src/backend/bootstrap/bootscanner.l,v 1.40 2005/06/29 22:51:54 tgl Exp $
 *
 *-------------------------------------------------------------------------
 */
#include "postgres.h"

#include "access/attnum.h"
#include "access/htup.h"
#include "access/itup.h"
#include "access/skey.h"
#include "access/tupdesc.h"
#include "bootstrap/bootstrap.h"
#include "catalog/pg_am.h"
#include "catalog/pg_attribute.h"
#include "catalog/pg_class.h"
#include "nodes/nodes.h"
#include "nodes/parsenodes.h"
#include "nodes/pg_list.h"
#include "nodes/primnodes.h"
#include "parser/scansup.h"
#include "rewrite/prs2lock.h"
#include "storage/block.h"
#include "storage/fd.h"
#include "storage/itemptr.h"
#include "storage/off.h"
#include "utils/rel.h"

/* Not needed now that this file is compiled as part of bootparse. */
/* #include "bootstrap_tokens.h" */


/* Avoid exit() on fatal scanner errors (a bit ugly -- see Int_yy_fatal_error) */
#undef fprintf
#define fprintf(file, fmt, msg)  ereport(ERROR, (errmsg_internal("%s", msg)))


static int	Int_yyline = 1;			/* line number for error reporting */

#line 640 "lex.Int_yy.c"
#line 641 "lex.Int_yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int Int_yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int Int_yylex_destroy ( void );

int Int_yyget_debug ( void );

void Int_yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE Int_yyget_extra ( void );

void Int_yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *Int_yyget_in ( void );

void Int_yyset_in  ( FILE * _in_str  );

FILE *Int_yyget_out ( void );

void Int_yyset_out  ( FILE * _out_str  );

			int Int_yyget_leng ( void );

char *Int_yyget_text ( void );

int Int_yyget_lineno ( void );

void Int_yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int Int_yywrap ( void );
#else
extern int Int_yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef Int_yytext_ptr
static void Int_yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int Int_yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int Int_yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( Int_yytext, (size_t) Int_yyleng, 1, Int_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->Int_yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( Int_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( Int_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (Int_yy_size_t) max_size, Int_yyin)) == 0 && ferror(Int_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(Int_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "Int_yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef Int_yyterminate
#define Int_yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) Int_yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int Int_yylex (void);

#define YY_DECL int Int_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after Int_yytext and Int_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( Int_yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->Int_yy_at_bol = \
				(Int_yytext[Int_yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	Int_yy_state_type Int_yy_current_state;
	char *Int_yy_cp, *Int_yy_bp;
	int Int_yy_act;
    
	if ( !(Int_yy_init) )
		{
		(Int_yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (Int_yy_start) )
			(Int_yy_start) = 1;	/* first start state */

		if ( ! Int_yyin )
			Int_yyin = stdin;

		if ( ! Int_yyout )
			Int_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			Int_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				Int_yy_create_buffer( Int_yyin, YY_BUF_SIZE );
		}

		Int_yy_load_buffer_state(  );
		}

	{
#line 66 "bootscanner.l"


#line 862 "lex.Int_yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		Int_yy_cp = (Int_yy_c_buf_p);

		/* Support of Int_yytext. */
		*Int_yy_cp = (Int_yy_hold_char);

		/* Int_yy_bp points to the position in Int_yy_ch_buf of the start of
		 * the current run.
		 */
		Int_yy_bp = Int_yy_cp;

		Int_yy_current_state = (Int_yy_start);
		Int_yy_current_state += YY_AT_BOL();
Int_yy_match:
		do
			{
			YY_CHAR Int_yy_c = Int_yy_ec[YY_SC_TO_UI(*Int_yy_cp)] ;
			if ( Int_yy_accept[Int_yy_current_state] )
				{
				(Int_yy_last_accepting_state) = Int_yy_current_state;
				(Int_yy_last_accepting_cpos) = Int_yy_cp;
				}
			while ( Int_yy_chk[Int_yy_base[Int_yy_current_state] + Int_yy_c] != Int_yy_current_state )
				{
				Int_yy_current_state = (int) Int_yy_def[Int_yy_current_state];
				if ( Int_yy_current_state >= 147 )
					Int_yy_c = Int_yy_meta[Int_yy_c];
				}
			Int_yy_current_state = Int_yy_nxt[Int_yy_base[Int_yy_current_state] + Int_yy_c];
			++Int_yy_cp;
			}
		while ( Int_yy_current_state != 146 );
		Int_yy_cp = (Int_yy_last_accepting_cpos);
		Int_yy_current_state = (Int_yy_last_accepting_state);

Int_yy_find_action:
		Int_yy_act = Int_yy_accept[Int_yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( Int_yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*Int_yy_cp = (Int_yy_hold_char);
			Int_yy_cp = (Int_yy_last_accepting_cpos);
			Int_yy_current_state = (Int_yy_last_accepting_state);
			goto Int_yy_find_action;

case 1:
YY_RULE_SETUP
#line 68 "bootscanner.l"
{ return(OPEN); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 70 "bootscanner.l"
{ return(XCLOSE); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 72 "bootscanner.l"
{ return(XCREATE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 74 "bootscanner.l"
{ return(OBJ_ID); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 75 "bootscanner.l"
{ return(XBOOTSTRAP); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 76 "bootscanner.l"
{ return(XSHARED_RELATION); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 77 "bootscanner.l"
{ return(XWITHOUT_OIDS); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 78 "bootscanner.l"
{ return(NULLVAL); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 80 "bootscanner.l"
{ return(INSERT_TUPLE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "bootscanner.l"
{ return(COMMA); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "bootscanner.l"
{ return(EQUALS); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "bootscanner.l"
{ return(LPAREN); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 85 "bootscanner.l"
{ return(RPAREN); }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 87 "bootscanner.l"
{ Int_yyline++; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 88 "bootscanner.l"
;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 89 "bootscanner.l"
;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 91 "bootscanner.l"
; /* drop everything after "#" for comments */
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 94 "bootscanner.l"
{ return(XDECLARE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 95 "bootscanner.l"
{ return(XBUILD); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 96 "bootscanner.l"
{ return(INDICES); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 97 "bootscanner.l"
{ return(UNIQUE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 98 "bootscanner.l"
{ return(INDEX); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 99 "bootscanner.l"
{ return(ON); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 100 "bootscanner.l"
{ return(USING); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 102 "bootscanner.l"
{
					Int_yylval.ival = EnterString(MapArrayTypeName((char*)Int_yytext));
					return(ID);
				}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 106 "bootscanner.l"
{
					char   *newid = scanstr((char*)Int_yytext);
					Int_yylval.ival = EnterString(newid);
					pfree(newid);
					return(ID);
				}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 112 "bootscanner.l"
{
					char   *newid;
					Int_yytext[strlen(Int_yytext)-1] = '\0'; /* strip off quotes */
					newid = scanstr((char*)Int_yytext+1);
					Int_yylval.ival = EnterString(newid);
					pfree(newid);
					Int_yytext[strlen(Int_yytext)] = '"'; /* restore quotes */
					return(ID);
				}
	YY_BREAK
case 28:
#line 123 "bootscanner.l"
case 29:
#line 124 "bootscanner.l"
case 30:
YY_RULE_SETUP
#line 124 "bootscanner.l"
{
							Int_yylval.ival = EnterString((char*)Int_yytext);
							return(CONST_P);
						}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 129 "bootscanner.l"
{
					elog(ERROR, "syntax error at line %d: unexpected character \"%s\"", Int_yyline, Int_yytext);
				}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 135 "bootscanner.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1093 "lex.Int_yy.c"
case YY_STATE_EOF(INITIAL):
	Int_yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int Int_yy_amount_of_matched_text = (int) (Int_yy_cp - (Int_yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*Int_yy_cp = (Int_yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->Int_yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed Int_yyin at a new source and called
			 * Int_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(Int_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->Int_yy_input_file = Int_yyin;
			YY_CURRENT_BUFFER_LVALUE->Int_yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for Int_yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since Int_yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (Int_yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[(Int_yy_n_chars)] )
			{ /* This was really a NUL. */
			Int_yy_state_type Int_yy_next_state;

			(Int_yy_c_buf_p) = (Int_yytext_ptr) + Int_yy_amount_of_matched_text;

			Int_yy_current_state = Int_yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * Int_yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			Int_yy_next_state = Int_yy_try_NUL_trans( Int_yy_current_state );

			Int_yy_bp = (Int_yytext_ptr) + YY_MORE_ADJ;

			if ( Int_yy_next_state )
				{
				/* Consume the NUL. */
				Int_yy_cp = ++(Int_yy_c_buf_p);
				Int_yy_current_state = Int_yy_next_state;
				goto Int_yy_match;
				}

			else
				{
				Int_yy_cp = (Int_yy_last_accepting_cpos);
				Int_yy_current_state = (Int_yy_last_accepting_state);
				goto Int_yy_find_action;
				}
			}

		else switch ( Int_yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(Int_yy_did_buffer_switch_on_eof) = 0;

				if ( Int_yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * Int_yy_get_next_buffer() to have set up
					 * Int_yytext, we can now set up
					 * Int_yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(Int_yy_c_buf_p) = (Int_yytext_ptr) + YY_MORE_ADJ;

					Int_yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (Int_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(Int_yy_c_buf_p) =
					(Int_yytext_ptr) + Int_yy_amount_of_matched_text;

				Int_yy_current_state = Int_yy_get_previous_state(  );

				Int_yy_cp = (Int_yy_c_buf_p);
				Int_yy_bp = (Int_yytext_ptr) + YY_MORE_ADJ;
				goto Int_yy_match;

			case EOB_ACT_LAST_MATCH:
				(Int_yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[(Int_yy_n_chars)];

				Int_yy_current_state = Int_yy_get_previous_state(  );

				Int_yy_cp = (Int_yy_c_buf_p);
				Int_yy_bp = (Int_yytext_ptr) + YY_MORE_ADJ;
				goto Int_yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of Int_yylex */

/* Int_yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int Int_yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf;
	char *source = (Int_yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (Int_yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[(Int_yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->Int_yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (Int_yy_c_buf_p) - (Int_yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((Int_yy_c_buf_p) - (Int_yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->Int_yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars = (Int_yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int Int_yy_c_buf_p_offset =
				(int) ((Int_yy_c_buf_p) - b->Int_yy_ch_buf);

			if ( b->Int_yy_is_our_buffer )
				{
				int new_size = b->Int_yy_buf_size * 2;

				if ( new_size <= 0 )
					b->Int_yy_buf_size += b->Int_yy_buf_size / 8;
				else
					b->Int_yy_buf_size *= 2;

				b->Int_yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					Int_yyrealloc( (void *) b->Int_yy_ch_buf,
							 (Int_yy_size_t) (b->Int_yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->Int_yy_ch_buf = NULL;

			if ( ! b->Int_yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(Int_yy_c_buf_p) = &b->Int_yy_ch_buf[Int_yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[number_to_move]),
			(Int_yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars = (Int_yy_n_chars);
		}

	if ( (Int_yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			Int_yyrestart( Int_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->Int_yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((Int_yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (Int_yy_n_chars) + number_to_move + ((Int_yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf = (char *) Int_yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf, (Int_yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in Int_yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_size = (int) (new_size - 2);
	}

	(Int_yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[(Int_yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[(Int_yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(Int_yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[0];

	return ret_val;
}

/* Int_yy_get_previous_state - get the state just before the EOB char was reached */

    static Int_yy_state_type Int_yy_get_previous_state (void)
{
	Int_yy_state_type Int_yy_current_state;
	char *Int_yy_cp;
    
	Int_yy_current_state = (Int_yy_start);
	Int_yy_current_state += YY_AT_BOL();

	for ( Int_yy_cp = (Int_yytext_ptr) + YY_MORE_ADJ; Int_yy_cp < (Int_yy_c_buf_p); ++Int_yy_cp )
		{
		YY_CHAR Int_yy_c = (*Int_yy_cp ? Int_yy_ec[YY_SC_TO_UI(*Int_yy_cp)] : 1);
		if ( Int_yy_accept[Int_yy_current_state] )
			{
			(Int_yy_last_accepting_state) = Int_yy_current_state;
			(Int_yy_last_accepting_cpos) = Int_yy_cp;
			}
		while ( Int_yy_chk[Int_yy_base[Int_yy_current_state] + Int_yy_c] != Int_yy_current_state )
			{
			Int_yy_current_state = (int) Int_yy_def[Int_yy_current_state];
			if ( Int_yy_current_state >= 147 )
				Int_yy_c = Int_yy_meta[Int_yy_c];
			}
		Int_yy_current_state = Int_yy_nxt[Int_yy_base[Int_yy_current_state] + Int_yy_c];
		}

	return Int_yy_current_state;
}

/* Int_yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = Int_yy_try_NUL_trans( current_state );
 */
    static Int_yy_state_type Int_yy_try_NUL_trans  (Int_yy_state_type Int_yy_current_state )
{
	int Int_yy_is_jam;
    	char *Int_yy_cp = (Int_yy_c_buf_p);

	YY_CHAR Int_yy_c = 1;
	if ( Int_yy_accept[Int_yy_current_state] )
		{
		(Int_yy_last_accepting_state) = Int_yy_current_state;
		(Int_yy_last_accepting_cpos) = Int_yy_cp;
		}
	while ( Int_yy_chk[Int_yy_base[Int_yy_current_state] + Int_yy_c] != Int_yy_current_state )
		{
		Int_yy_current_state = (int) Int_yy_def[Int_yy_current_state];
		if ( Int_yy_current_state >= 147 )
			Int_yy_c = Int_yy_meta[Int_yy_c];
		}
	Int_yy_current_state = Int_yy_nxt[Int_yy_base[Int_yy_current_state] + Int_yy_c];
	Int_yy_is_jam = (Int_yy_current_state == 146);

		return Int_yy_is_jam ? 0 : Int_yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int Int_yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(Int_yy_c_buf_p) = (Int_yy_hold_char);

	if ( *(Int_yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* Int_yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (Int_yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->Int_yy_ch_buf[(Int_yy_n_chars)] )
			/* This was really a NUL. */
			*(Int_yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((Int_yy_c_buf_p) - (Int_yytext_ptr));
			++(Int_yy_c_buf_p);

			switch ( Int_yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because Int_yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					Int_yyrestart( Int_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( Int_yywrap(  ) )
						return 0;

					if ( ! (Int_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return Int_yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(Int_yy_c_buf_p) = (Int_yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (Int_yy_c_buf_p);	/* cast for 8-bit char's */
	*(Int_yy_c_buf_p) = '\0';	/* preserve Int_yytext */
	(Int_yy_hold_char) = *++(Int_yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->Int_yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void Int_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        Int_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            Int_yy_create_buffer( Int_yyin, YY_BUF_SIZE );
	}

	Int_yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	Int_yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void Int_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		Int_yypop_buffer_state();
	 *		Int_yypush_buffer_state(new_buffer);
     */
	Int_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(Int_yy_c_buf_p) = (Int_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_pos = (Int_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars = (Int_yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	Int_yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (Int_yywrap()) processing, but the only time this flag
	 * is looked at is after Int_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(Int_yy_did_buffer_switch_on_eof) = 1;
}

static void Int_yy_load_buffer_state  (void)
{
    	(Int_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars;
	(Int_yytext_ptr) = (Int_yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_pos;
	Int_yyin = YY_CURRENT_BUFFER_LVALUE->Int_yy_input_file;
	(Int_yy_hold_char) = *(Int_yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE Int_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) Int_yyalloc( sizeof( struct Int_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Int_yy_create_buffer()" );

	b->Int_yy_buf_size = size;

	/* Int_yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->Int_yy_ch_buf = (char *) Int_yyalloc( (Int_yy_size_t) (b->Int_yy_buf_size + 2)  );
	if ( ! b->Int_yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in Int_yy_create_buffer()" );

	b->Int_yy_is_our_buffer = 1;

	Int_yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with Int_yy_create_buffer()
 * 
 */
    void Int_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->Int_yy_is_our_buffer )
		Int_yyfree( (void *) b->Int_yy_ch_buf  );

	Int_yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a Int_yyrestart() or at EOF.
 */
    static void Int_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	Int_yy_flush_buffer( b );

	b->Int_yy_input_file = file;
	b->Int_yy_fill_buffer = 1;

    /* If b is the current buffer, then Int_yy_init_buffer was _probably_
     * called from Int_yyrestart() or through Int_yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->Int_yy_bs_lineno = 1;
        b->Int_yy_bs_column = 0;
    }

        b->Int_yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void Int_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->Int_yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->Int_yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->Int_yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->Int_yy_buf_pos = &b->Int_yy_ch_buf[0];

	b->Int_yy_at_bol = 1;
	b->Int_yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		Int_yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void Int_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	Int_yyensure_buffer_stack();

	/* This block is copied from Int_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(Int_yy_c_buf_p) = (Int_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->Int_yy_buf_pos = (Int_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->Int_yy_n_chars = (Int_yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(Int_yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from Int_yy_switch_to_buffer. */
	Int_yy_load_buffer_state(  );
	(Int_yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void Int_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	Int_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((Int_yy_buffer_stack_top) > 0)
		--(Int_yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		Int_yy_load_buffer_state(  );
		(Int_yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void Int_yyensure_buffer_stack (void)
{
	Int_yy_size_t num_to_alloc;
    
	if (!(Int_yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(Int_yy_buffer_stack) = (struct Int_yy_buffer_state**)Int_yyalloc
								(num_to_alloc * sizeof(struct Int_yy_buffer_state*)
								);
		if ( ! (Int_yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Int_yyensure_buffer_stack()" );

		memset((Int_yy_buffer_stack), 0, num_to_alloc * sizeof(struct Int_yy_buffer_state*));

		(Int_yy_buffer_stack_max) = num_to_alloc;
		(Int_yy_buffer_stack_top) = 0;
		return;
	}

	if ((Int_yy_buffer_stack_top) >= ((Int_yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		Int_yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (Int_yy_buffer_stack_max) + grow_size;
		(Int_yy_buffer_stack) = (struct Int_yy_buffer_state**)Int_yyrealloc
								((Int_yy_buffer_stack),
								num_to_alloc * sizeof(struct Int_yy_buffer_state*)
								);
		if ( ! (Int_yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in Int_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((Int_yy_buffer_stack) + (Int_yy_buffer_stack_max), 0, grow_size * sizeof(struct Int_yy_buffer_state*));
		(Int_yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE Int_yy_scan_buffer  (char * base, Int_yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) Int_yyalloc( sizeof( struct Int_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in Int_yy_scan_buffer()" );

	b->Int_yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->Int_yy_buf_pos = b->Int_yy_ch_buf = base;
	b->Int_yy_is_our_buffer = 0;
	b->Int_yy_input_file = NULL;
	b->Int_yy_n_chars = b->Int_yy_buf_size;
	b->Int_yy_is_interactive = 0;
	b->Int_yy_at_bol = 1;
	b->Int_yy_fill_buffer = 0;
	b->Int_yy_buffer_status = YY_BUFFER_NEW;

	Int_yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to Int_yylex() will
 * scan from a @e copy of @a str.
 * @param Int_yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       Int_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE Int_yy_scan_string (const char * Int_yystr )
{
    
	return Int_yy_scan_bytes( Int_yystr, (int) strlen(Int_yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to Int_yylex() will
 * scan from a @e copy of @a bytes.
 * @param Int_yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE Int_yy_scan_bytes  (const char * Int_yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	Int_yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (Int_yy_size_t) (_yybytes_len + 2);
	buf = (char *) Int_yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in Int_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = Int_yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = Int_yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in Int_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->Int_yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void Int_yynoreturn Int_yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine Int_yyless() so it works in section 3 code. */

#undef Int_yyless
#define Int_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up Int_yytext. */ \
        int Int_yyless_macro_arg = (n); \
        YY_LESS_LINENO(Int_yyless_macro_arg);\
		Int_yytext[Int_yyleng] = (Int_yy_hold_char); \
		(Int_yy_c_buf_p) = Int_yytext + Int_yyless_macro_arg; \
		(Int_yy_hold_char) = *(Int_yy_c_buf_p); \
		*(Int_yy_c_buf_p) = '\0'; \
		Int_yyleng = Int_yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int Int_yyget_lineno  (void)
{
    
    return Int_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *Int_yyget_in  (void)
{
        return Int_yyin;
}

/** Get the output stream.
 * 
 */
FILE *Int_yyget_out  (void)
{
        return Int_yyout;
}

/** Get the length of the current token.
 * 
 */
int Int_yyget_leng  (void)
{
        return Int_yyleng;
}

/** Get the current token.
 * 
 */

char *Int_yyget_text  (void)
{
        return Int_yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void Int_yyset_lineno (int  _line_number )
{
    
    Int_yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see Int_yy_switch_to_buffer
 */
void Int_yyset_in (FILE *  _in_str )
{
        Int_yyin = _in_str ;
}

void Int_yyset_out (FILE *  _out_str )
{
        Int_yyout = _out_str ;
}

int Int_yyget_debug  (void)
{
        return Int_yy_flex_debug;
}

void Int_yyset_debug (int  _bdebug )
{
        Int_yy_flex_debug = _bdebug ;
}

static int Int_yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from Int_yylex_destroy(), so don't allocate here.
     */

    (Int_yy_buffer_stack) = NULL;
    (Int_yy_buffer_stack_top) = 0;
    (Int_yy_buffer_stack_max) = 0;
    (Int_yy_c_buf_p) = NULL;
    (Int_yy_init) = 0;
    (Int_yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    Int_yyin = stdin;
    Int_yyout = stdout;
#else
    Int_yyin = NULL;
    Int_yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * Int_yylex_init()
     */
    return 0;
}

/* Int_yylex_destroy is for both reentrant and non-reentrant scanners. */
int Int_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		Int_yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		Int_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	Int_yyfree((Int_yy_buffer_stack) );
	(Int_yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * Int_yylex() is called, initialization will occur. */
    Int_yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef Int_yytext_ptr
static void Int_yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int Int_yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *Int_yyalloc (Int_yy_size_t  size )
{
			return malloc(size);
}

void *Int_yyrealloc  (void * ptr, Int_yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void Int_yyfree (void * ptr )
{
			free( (char *) ptr );	/* see Int_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "Int_yytables"

#line 135 "bootscanner.l"


void
Int_yyerror(const char *message)
{
	elog(ERROR, "%s at line %d", message, Int_yyline);
}

